---
driver:
  name: docker

platforms:
  - name: firewall-ubuntu2404
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      stdout_callback: yaml
      callbacks_enabled: profile_tasks
  inventory:
    host_vars:
      firewall-ubuntu2404:
        ansible_user: root

verifier:
  name: ansible
